#!/usr/bin/env node
// postbuild-crypto.mjs — fix dist/crypto.js's tweetnacl-util import after tsc.
//
// `tsc` emits `import { encodeBase64, decodeBase64 } from 'tweetnacl-util'`, but
// tweetnacl-util is CommonJS with only a default export — that named ESM import
// resolves to `undefined` at runtime under Node's ESM loader. We rewrite it to a
// default import + destructure so the named bindings work.
//
// This replaces the previous inline `node -e "...replace('…\\n…')"` in
// package.json (run as `prepare` + `pretest`). That `\n` only became a real
// newline under a POSIX shell; on Windows the script ran via cmd.exe/PowerShell,
// which wrote a LITERAL backslash-n into line 2 of dist/crypto.js — a SyntaxError
// on import that broke `chroxy init`/`start`. A real .mjs with an ordinary JS
// string sidesteps the cross-shell quoting trap entirely.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const distFile = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist', 'crypto.js')

const FROM = "import { encodeBase64, decodeBase64 } from 'tweetnacl-util';"
const TO = "import naclUtil from 'tweetnacl-util';\nconst { encodeBase64, decodeBase64 } = naclUtil;"

const original = readFileSync(distFile, 'utf8')

if (!original.includes(FROM)) {
  // Idempotent: a re-run after a previous successful rewrite is a no-op.
  if (original.includes("import naclUtil from 'tweetnacl-util'")) {
    process.exit(0)
  }
  console.error(
    `[postbuild-crypto] expected tweetnacl-util named import not found in ${distFile}.\n` +
    "  tsc's emit may have changed — update FROM/TO in this script.",
  )
  process.exit(1)
}

// Normalise to LF so the committed artifact is byte-deterministic across
// platforms (the repo blob is LF; dist/crypto.js is force-committed via a
// .gitignore negation and regenerated by prepare/pretest).
let rewritten = original.replace(FROM, TO).replace(/\r\n/g, '\n')

// Strip a leading UTF-8 BOM (0xFEFF) if tsc ever emits one — keeps the first
// import statement at byte 0 so the artifact stays deterministic.
if (rewritten.charCodeAt(0) === 0xfeff) {
  rewritten = rewritten.slice(1)
}

writeFileSync(distFile, rewritten, { encoding: 'utf8' })
