#!/usr/bin/env bash
#
# bump-version.test.sh — Self-contained test harness for scripts/bump-version.sh.
#
# Runs in a temp dir with a minimal fake monorepo skeleton (just the file paths
# bump-version.sh writes to). Each test case asserts an observable behavior of
# the script. No external test framework — keeps CI dep surface zero.
#
# Run from repo root:
#   bash scripts/__tests__/bump-version.test.sh
#
# Exit status: 0 if all tests pass, 1 otherwise.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BUMP="$REPO_ROOT/scripts/bump-version.sh"

PASS=0
FAIL=0
FAILED_TESTS=()

# PATH stripped of cargo so the lockfile-sync block deterministically takes
# the awk-in-place fallback. Tests that need to exercise the `command -v
# cargo` branch install a stub via install_cargo_stub() and prepend its
# directory to this value.
#
# Computed by walking the inherited $PATH and dropping every entry that
# actually contains a `cargo` executable. The remaining entries still give
# the script `node`, `awk`, `grep`, `sed`, `date`, etc. — every other
# external tool bump-version.sh shells out to. A hardcoded list would have
# to track per-runner Node layouts (CI uses /opt/hostedtoolcache, devs use
# /opt/homebrew or volta, nix uses /nix/store, etc.).
__strip_cargo_from_path() {
  local p="$1"
  local out=""
  local IFS=":"
  for d in $p; do
    [ -n "$d" ] || continue
    [ -x "$d/cargo" ] && continue
    if [ -z "$out" ]; then
      out="$d"
    else
      out="$out:$d"
    fi
  done
  printf '%s\n' "$out"
}
NOCARGO_PATH="$(__strip_cargo_from_path "$PATH")"

# --- helpers -----------------------------------------------------------------

# Build a minimal fake repo at $1 that satisfies every path bump-version.sh
# touches. Versions all start at $2.
#
# Cargo.lock includes a realistic `chroxy-desktop` stanza AND a transitive
# dependency at the same version — the lockfile-sync block must only rewrite
# the workspace stanza, never the look-alike transitive. The harness reuses
# the same fixture so every successful-bump test indirectly guards against the
# false-match regression.
build_fake_repo() {
  local dir="$1"
  local v="$2"
  mkdir -p "$dir/packages/server" "$dir/packages/app/ios/Chroxy" \
           "$dir/packages/desktop/src-tauri" "$dir/packages/protocol" \
           "$dir/packages/store-core" "$dir/packages/dashboard" \
           "$dir/packages/claude-hooks" "$dir/packages/design-tokens"

  for pkg in server app desktop protocol store-core dashboard claude-hooks design-tokens; do
    printf '{"name":"%s","version":"%s"}\n' "$pkg" "$v" \
      > "$dir/packages/$pkg/package.json"
  done
  printf '{"name":"chroxy","version":"%s"}\n' "$v" > "$dir/package.json"
  printf '{"expo":{"name":"chroxy","version":"%s"}}\n' "$v" \
    > "$dir/packages/app/app.json"
  printf '{"version":"%s"}\n' "$v" \
    > "$dir/packages/desktop/src-tauri/tauri.conf.json"
  cat > "$dir/packages/desktop/src-tauri/Cargo.toml" <<EOF
[package]
name = "chroxy-desktop"
version = "$v"
edition = "2021"
EOF
  cat > "$dir/packages/app/ios/Chroxy/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
  <key>CFBundleShortVersionString</key>
  <string>$v</string>
</dict>
</plist>
EOF
  printf '{"version":"%s","packages":{"":{"version":"%s"}}}\n' "$v" "$v" \
    > "$dir/package-lock.json"
  printf '{"version":"%s","packages":{"":{"version":"%s"}}}\n' "$v" "$v" \
    > "$dir/packages/server/package-lock.json"

  # Minimal Cargo.lock mirroring the shape of the real one. The decoy stanza
  # is a synthetic transitive at the same version — the lockfile-sync block
  # must scope its rewrite to the `chroxy-desktop` stanza only.
  cat > "$dir/packages/desktop/src-tauri/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "decoy-dep"
version = "$v"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"

[[package]]
name = "chroxy-desktop"
version = "$v"
dependencies = [
 "serde",
 "tauri",
]

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafebabe"
EOF
}

# Copy bump-version.sh into the fake repo. No source mutation — the script
# runs as-is, and PATH control (via NOCARGO_PATH / install_cargo_stub) picks
# which branch of the lockfile-sync block is exercised.
install_bump_script() {
  local dir="$1"
  mkdir -p "$dir/scripts"
  cp "$BUMP" "$dir/scripts/bump-version.sh"
  chmod +x "$dir/scripts/bump-version.sh"
}

# Install a `cargo` shim that performs the same in-place rewrite the awk
# fallback would, and drops a sentinel file so tests can assert the cargo
# branch was actually taken (i.e., the script didn't fall through to awk).
# Returns the directory holding the shim — caller is responsible for putting
# it on $PATH before running the bump.
install_cargo_stub() {
  local dir="$1"
  local stubdir="$dir/.stub-bin"
  mkdir -p "$stubdir"
  cat > "$stubdir/cargo" <<'STUB'
#!/usr/bin/env bash
# Minimal cargo stub: parse --precise <V> from argv, rewrite the
# chroxy-desktop stanza in ./Cargo.lock, drop a sentinel so the test can
# prove this branch ran instead of the awk fallback.
set -euo pipefail
new=""
while [ $# -gt 0 ]; do
  case "$1" in
    --precise) new="$2"; shift 2 ;;
    *) shift ;;
  esac
done
[ -n "$new" ] || { echo "cargo stub: missing --precise" >&2; exit 1; }
: > "$PWD/.cargo-stub-ran"
tmp="$PWD/Cargo.lock.stub.tmp"
awk -v new="$new" '
  /^\[\[package\]\]/ { in_pkg = 1; is_target = 0 }
  in_pkg && /^name = "chroxy-desktop"$/ { is_target = 1 }
  in_pkg && is_target && /^version = "/ {
    sub(/^version = "[^"]*"/, "version = \"" new "\"")
    is_target = 0
  }
  /^$/ { in_pkg = 0; is_target = 0 }
  { print }
' "$PWD/Cargo.lock" > "$tmp" && mv "$tmp" "$PWD/Cargo.lock"
STUB
  chmod +x "$stubdir/cargo"
  echo "$stubdir"
}

# Copy the real gen-agents-md.mjs into a fake repo, plus anything it imports.
#
# Copying scripts/lib wholesale rather than naming a file. The directory does
# not exist on this branch; #7222 proposes extracting the entry-point guard
# there, and a fixture that stages only gen-agents-md.mjs dies with
# ERR_MODULE_NOT_FOUND the moment the generator gains a sibling import. The
# `[ -d ]` guard below means this works either way, before or after that lands,
# and stages the NEXT extraction automatically too.
install_agents_generator() {
  local dir="$1"
  mkdir -p "$dir/scripts"
  cp "$REPO_ROOT/scripts/gen-agents-md.mjs" "$dir/scripts/gen-agents-md.mjs"
  if [ -d "$REPO_ROOT/scripts/lib" ]; then
    cp -R "$REPO_ROOT/scripts/lib" "$dir/scripts/lib"
  fi
}

# A CLAUDE.md carrying both version markers the bump rewrites. Without them the
# bump aborts before it ever reaches the AGENTS.md block (#7183).
write_claude_md() {
  cat > "$1" <<CLAUDEMD
# Claude Development Notes

**Current Status (v$2):**
- stuff works

---

*Last Updated: 2026-01-01*
*Version: $2*
CLAUDEMD
}

# Write a minimal CHANGELOG.md (header + one prior section).
write_changelog() {
  local file="$1"
  local prev_version="$2"
  local prev_body="$3"
  cat > "$file" <<EOF
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [$prev_version] - 2026-01-01

$prev_body
EOF
}

run_test() {
  local name="$1"
  shift
  if "$@"; then
    PASS=$((PASS + 1))
    echo "  PASS  $name"
  else
    FAIL=$((FAIL + 1))
    FAILED_TESTS+=("$name")
    echo "  FAIL  $name"
  fi
}

# --- test cases --------------------------------------------------------------

test_scaffolds_new_section() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- Some prior fix (#1)"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # New section header present, on its own line, with today's date
  local today
  today=$(date +%Y-%m-%d)
  grep -q "^## \[0.2.0\] - $today\$" "$dir/CHANGELOG.md" || {
    echo "    expected: ## [0.2.0] - $today" >&2
    return 1
  }

  # All three placeholder sections present
  grep -q "^### Added\$" "$dir/CHANGELOG.md" || return 1
  grep -q "^### Changed\$" "$dir/CHANGELOG.md" || return 1
  grep -q "^### Fixed\$" "$dir/CHANGELOG.md" || return 1

  # TODO markers present (drift guard fodder)
  [ "$(grep -c '^- TODO:' "$dir/CHANGELOG.md")" -eq 3 ] || return 1

  # Prior section preserved
  grep -q "^## \[0.1.0\] - 2026-01-01" "$dir/CHANGELOG.md" || return 1
  grep -q "Some prior fix" "$dir/CHANGELOG.md" || return 1

  # New section appears BEFORE the prior section (Keep-a-Changelog ordering)
  local new_line prev_line
  new_line=$(grep -n "^## \[0.2.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  prev_line=$(grep -n "^## \[0.1.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  [ "$new_line" -lt "$prev_line" ]
}

test_inserts_after_unreleased_section() {
  # #5207 — when the CHANGELOG has an [Unreleased] section on top, the new
  # versioned section must land directly BELOW it (and its body), not above —
  # preserving Keep-a-Changelog ordering and not burying pending entries.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

The format is based on [Keep a Changelog]; [Unreleased] stays on top.

## [Unreleased]

### Added

- A pending entry not yet released

## [0.1.0] - 2026-01-01

### Added

- Initial release
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  grep -q "^## \[0.2.0\] - " "$dir/CHANGELOG.md" || return 1

  # Ordering must be: [Unreleased] < [0.2.0] < [0.1.0]
  local unrel_line new_line prev_line
  unrel_line=$(grep -n "^## \[Unreleased\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  new_line=$(grep -n "^## \[0.2.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  prev_line=$(grep -n "^## \[0.1.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  [ "$unrel_line" -lt "$new_line" ] || {
    echo "    new section landed above [Unreleased] (line $new_line vs $unrel_line)" >&2
    return 1
  }
  [ "$new_line" -lt "$prev_line" ] || {
    echo "    new section landed below the prior release (line $new_line vs $prev_line)" >&2
    return 1
  }

  # The pending [Unreleased] entry must be preserved (not buried/dropped) AND
  # stay above the new version header — i.e. the new section must land below the
  # [Unreleased] *body*, not immediately after the `## [Unreleased]` line (which
  # would push the pending entry under the cut release). Assert by line number,
  # not just existence, so a regression that splices after the header line fails.
  local pending_line
  pending_line=$(grep -n "A pending entry not yet released" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  [ -n "$pending_line" ] || {
    echo "    pending [Unreleased] entry was dropped" >&2
    return 1
  }
  [ "$pending_line" -lt "$new_line" ] || {
    echo "    pending [Unreleased] entry landed below the new section (line $pending_line vs $new_line)" >&2
    return 1
  }
}

test_preserves_header_preamble() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Added

- Initial release"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # The Keep-a-Changelog preamble lines must still be the first non-blank lines
  head -5 "$dir/CHANGELOG.md" | grep -q "^# Changelog\$" || return 1
  head -10 "$dir/CHANGELOG.md" | grep -q "Keep a Changelog" || return 1
}

test_idempotent_when_section_exists() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.2.0] - 2026-05-15

### Added

- Already documented this release manually

## [0.1.0] - 2026-01-01

### Added

- Initial release
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # The pre-existing 0.2.0 section must survive untouched — no duplicate
  # header, no TODO injection.
  [ "$(grep -c '^## \[0.2.0\]' "$dir/CHANGELOG.md")" -eq 1 ] || return 1
  ! grep -q "^- TODO:" "$dir/CHANGELOG.md" || return 1
  grep -q "Already documented this release manually" "$dir/CHANGELOG.md" || return 1
}

test_blocks_when_prior_todo_unresolved() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.1.0] - 2026-01-01

### Added

- TODO: describe additions for this release (or delete this section)
EOF

  local output
  output=$(cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0 2>&1)
  local status=$?

  # Script must exit non-zero
  [ "$status" -ne 0 ] || {
    echo "    expected non-zero exit, got 0" >&2
    return 1
  }

  # Error message must reference the TODO placeholder
  echo "$output" | grep -q "TODO" || {
    echo "    error message did not mention TODO: $output" >&2
    return 1
  }

  # CHANGELOG must be unchanged (no 0.2.0 section)
  ! grep -q "^## \[0.2.0\]" "$dir/CHANGELOG.md" || return 1
}

test_no_changelog_flag_skips_scaffold() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  # Deliberately set up a CHANGELOG with an unresolved TODO — the flag must
  # still allow the bump to proceed.
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.1.0] - 2026-01-01

### Added

- TODO: describe additions for this release (or delete this section)
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh --no-changelog 0.2.0) > /dev/null 2>&1 || return 1

  # Version files updated
  grep -qE '"version":\s*"0.2.0"' "$dir/packages/server/package.json" || return 1
  # CHANGELOG.md untouched (still no 0.2.0 section)
  ! grep -q "^## \[0.2.0\]" "$dir/CHANGELOG.md" || return 1
}

test_no_changelog_flag_before_version() {
  # Flag order must not matter — --no-changelog can come before or after the
  # version positional.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Added

- Initial release"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0 --no-changelog) > /dev/null 2>&1 || return 1
  ! grep -q "^## \[0.2.0\]" "$dir/CHANGELOG.md" || return 1
}

test_auto_bump_patch_with_scaffold() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh) > /dev/null 2>&1 || return 1

  # Auto-bumped to 0.5.8 and scaffolded
  grep -qE '"version":\s*"0.5.8"' "$dir/packages/server/package.json" || return 1
  grep -q "^## \[0.5.8\] - " "$dir/CHANGELOG.md" || return 1
}

test_only_checks_most_recent_section_for_todo() {
  # A stale TODO in an OLD section (older than the most-recent) must NOT block
  # the bump — otherwise every bump after a missed CHANGELOG update would be
  # permanently blocked.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.2.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.2.0] - 2026-02-01

### Added

- Properly documented this one

## [0.1.0] - 2026-01-01

### Added

- TODO: describe additions for this release (or delete this section)
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.3.0) > /dev/null 2>&1 || {
    echo "    bump unexpectedly failed despite stale TODO being in OLD section" >&2
    return 1
  }
  grep -q "^## \[0.3.0\]" "$dir/CHANGELOG.md" || return 1
}

test_help_prints_full_header() {
  # The header comment block expanded from 9 lines to 16+ in this PR. Earlier
  # versions of --help printed a hardcoded line range (2,11) and silently
  # truncated. Lock the contract: --help must include both the usage block
  # AND the CHANGELOG scaffolding paragraph.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"

  local output
  output=$(cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh --help 2>&1)
  [ $? -eq 0 ] || return 1

  echo "$output" | grep -q "Usage:" || {
    echo "    --help missing 'Usage:'" >&2
    return 1
  }
  echo "$output" | grep -q "no-changelog" || {
    echo "    --help missing '--no-changelog' line" >&2
    return 1
  }
  echo "$output" | grep -q "CHANGELOG scaffolding" || {
    echo "    --help truncated before CHANGELOG scaffolding paragraph" >&2
    return 1
  }
}

test_rejects_unknown_flag() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh --bogus-flag 0.2.0) > /dev/null 2>&1
  [ $? -ne 0 ]
}

# --- Cargo.lock sync coverage (#4253) ---------------------------------------

test_lockfile_awk_rewrites_only_chroxy_desktop() {
  # The awk fallback must rewrite the `chroxy-desktop` stanza only — a
  # transitive dep that happens to share the same version string must stay
  # pinned to its original version.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  local lock="$dir/packages/desktop/src-tauri/Cargo.lock"

  # The chroxy-desktop stanza moved to 0.2.0.
  awk '
    /^\[\[package\]\]/ { in_pkg = 1; is_target = 0; next }
    in_pkg && /^name = "chroxy-desktop"$/ { is_target = 1; next }
    in_pkg && is_target && /^version = "/ {
      sub(/^version = "/, ""); sub(/".*$/, ""); print; exit
    }
    /^$/ { in_pkg = 0; is_target = 0 }
  ' "$lock" | grep -qx "0.2.0" || {
    echo "    chroxy-desktop stanza did not move to 0.2.0" >&2
    return 1
  }

  # The decoy stanza (same starting version, different name) stayed at 0.1.0
  # — a bare grep/sed on `version = "0.1.0"` would have rewritten this too.
  awk '
    /^\[\[package\]\]/ { in_pkg = 1; is_target = 0; next }
    in_pkg && /^name = "decoy-dep"$/ { is_target = 1; next }
    in_pkg && is_target && /^version = "/ {
      sub(/^version = "/, ""); sub(/".*$/, ""); print; exit
    }
    /^$/ { in_pkg = 0; is_target = 0 }
  ' "$lock" | grep -qx "0.1.0" || {
    echo "    decoy-dep stanza was incorrectly rewritten (false-match regression)" >&2
    return 1
  }
}

test_lockfile_verify_fails_when_stanza_missing() {
  # If Cargo.lock has no chroxy-desktop stanza (corruption, accidental
  # delete, untracked checkout), the post-verify must abort with a non-zero
  # exit — silent success would let CI ship a stale lockfile.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  # Replace the seeded Cargo.lock with one missing the chroxy-desktop stanza.
  cat > "$dir/packages/desktop/src-tauri/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafebabe"
EOF

  local output status
  output=$(cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0 2>&1)
  status=$?

  [ "$status" -ne 0 ] || {
    echo "    expected non-zero exit when chroxy-desktop stanza is missing, got 0" >&2
    return 1
  }
  echo "$output" | grep -q "Cargo.lock" || {
    echo "    error message did not mention Cargo.lock: $output" >&2
    return 1
  }
}

test_lockfile_uses_cargo_when_on_path() {
  # When cargo is on PATH, the script must take the cargo branch and not
  # fall through to the awk fallback. Detect via a sentinel file the stub
  # drops next to Cargo.lock — the awk path never touches that file.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  local stubdir
  stubdir=$(install_cargo_stub "$dir")

  (cd "$dir" && PATH="$stubdir:$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # Stub left its sentinel — proves the cargo branch ran.
  [ -f "$dir/packages/desktop/src-tauri/.cargo-stub-ran" ] || {
    echo "    cargo stub sentinel missing — script fell through to awk fallback" >&2
    return 1
  }

  # And the lockfile is still consistent (stub uses the same awk edit).
  local lock="$dir/packages/desktop/src-tauri/Cargo.lock"
  awk '
    /^\[\[package\]\]/ { in_pkg = 1; is_target = 0; next }
    in_pkg && /^name = "chroxy-desktop"$/ { is_target = 1; next }
    in_pkg && is_target && /^version = "/ {
      sub(/^version = "/, ""); sub(/".*$/, ""); print; exit
    }
    /^$/ { in_pkg = 0; is_target = 0 }
  ' "$lock" | grep -qx "0.2.0"
}


# --- workspace @chroxy/* dependency ranges (#7187) ---------------------------

# The ranges are bounded (^X.Y.Z) so a PUBLISHED package can never acquire a
# breaking sibling. That bound is only safe if the bump moves it: a package
# left at the previous minor stops matching its sibling in the workspace, and
# npm silently resolves it from the registry instead of linking locally.
test_bumps_workspace_chroxy_dep_ranges() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"

  # server depends on two siblings at the CURRENT version, plus a third-party
  # dep that must be left alone (the negative control).
  printf '{"name":"server","version":"0.5.7","dependencies":{"@chroxy/protocol":"^0.5.7","commander":"^12.1.0"},"devDependencies":{"@chroxy/store-core":"^0.5.7"}}\n' \
    > "$dir/packages/server/package.json"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) > /dev/null 2>&1 || return 1

  # Both @chroxy/* ranges moved to the new version, in BOTH dependency fields.
  grep -q '"@chroxy/protocol": "\^0.6.0"' "$dir/packages/server/package.json" || return 1
  grep -q '"@chroxy/store-core": "\^0.6.0"' "$dir/packages/server/package.json" || return 1
  # Negative control: a third-party range is untouched. Without this, a rewrite
  # that clobbered every dependency would pass the assertions above.
  grep -q '"commander": "\^12.1.0"' "$dir/packages/server/package.json" || return 1
  # And the stale range is gone entirely.
  ! grep -q '0.5.7' "$dir/packages/server/package.json" || return 1
}


# --- CLAUDE.md / AGENTS.md version references (#7183) ------------------------

# These two lines are the first thing a session reads about "what version is
# this". Nothing rewrote them, so at the 0.10.0 -> 0.11.0 bump the header still
# said v0.10.0 and the footer still said 0.9.47 — two releases stale.
test_bumps_claude_md_version_references() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"

  cat > "$dir/CLAUDE.md" <<'CLAUDEMD'
# Claude Development Notes

**Current Status (v0.5.7):**
- stuff works

---

*Last Updated: 2026-01-01*
*Version: 0.5.7*
CLAUDEMD

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) > /dev/null 2>&1 || return 1

  grep -q '^\*\*Current Status (v0.6.0):\*\*' "$dir/CLAUDE.md" || return 1
  grep -q '^\*Version: 0.6.0\*$' "$dir/CLAUDE.md" || return 1
  # Negative control: an unrelated version-shaped line is untouched. Without
  # this, a rewrite that clobbered every semver in the file would pass above.
  grep -q '^\*Last Updated: 2026-01-01\*$' "$dir/CLAUDE.md" || return 1
  ! grep -q '0\.5\.7' "$dir/CLAUDE.md" || return 1
}

# The script must still run against a tree with no CLAUDE.md — the other
# fixtures build exactly that, and a hard failure here would break them all.
test_bump_survives_missing_claude_md() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"
  rm -f "$dir/CLAUDE.md"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) > /dev/null 2>&1 || return 1
  grep -qE '"version":\s*"0.6.0"' "$dir/packages/server/package.json" || return 1
}


# A reworded CLAUDE.md must ABORT, not silently skip. Skipping is a fail-open
# on the exact drift this closes: the rewrite does nothing, the script reports
# success, and the version goes stale again unnoticed.
test_aborts_when_claude_md_format_changed() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"

  # Both markers reworded — the format drift the guard must catch.
  cat > "$dir/CLAUDE.md" <<'CLAUDEMD'
# Claude Development Notes

**Status as of v0.5.7:**
- stuff works

*Release: 0.5.7*
CLAUDEMD

  # Must fail...
  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) > /dev/null 2>&1 && return 1
  # ...and say why.
  local out
  out=$( (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) 2>&1 || true )
  echo "$out" | grep -q "does not contain the expected version reference" || return 1
  return 0
}

# --- AGENTS.md verified in the caller's frame (#7231) ------------------------
#
# bump-version.sh regenerates AGENTS.md and then has to prove it worked. It used
# to prove it by re-invoking the same program whose reliability is in question
# — and that program resolves its own paths from import.meta.url, so `--check`
# graded THE GENERATOR'S AGENTS.md, never "$ROOT/AGENTS.md". Write and check
# were self-consistent by construction and agreed with each other whether or not
# the caller's mirror was ever touched.
#
# The three cases below are one positive control and two independent routes to
# the same false success. Without the control, both failure tests would pass on
# a fixture where the bump aborts for some unrelated reason.

# POSITIVE CONTROL. With the real generator and a well-formed tree, the bump
# must SUCCEED and $ROOT/AGENTS.md must actually be the render of the
# POST-bump CLAUDE.md — not the pre-bump one, which is what a check running
# before the version rewrite would accept.
test_agents_md_regenerated_and_verified_in_root_frame() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  install_agents_generator "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"
  write_claude_md "$dir/CLAUDE.md" "0.5.7"
  printf 'STALE\n' > "$dir/AGENTS.md"

  local out
  out=$( (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) 2>&1 ) || return 1
  echo "$out" | grep -q "AGENTS.md regenerated from CLAUDE.md" || return 1

  # The mirror really moved...
  ! grep -q '^STALE$' "$dir/AGENTS.md" || return 1
  # ...and carries the BUMPED version, so the regeneration happened after the
  # CLAUDE.md rewrite rather than before it.
  grep -q '^\*Version: 0.6.0\*$' "$dir/AGENTS.md" || return 1
  grep -q 'AUTO-GENERATED FROM CLAUDE.md' "$dir/AGENTS.md" || return 1
}

# The #7231 case proper — the generator resolves to a DIFFERENT TREE. $ROOT/scripts/
# gen-agents-md.mjs is a symlink, so node resolves import.meta.url to the other
# tree and the CLI writes THAT tree's AGENTS.md. Under the old check the bump
# printed its success line and exited 0 with $ROOT/AGENTS.md untouched.
test_agents_md_fails_when_generator_writes_to_another_tree() {
  local dir other
  dir=$(mktemp -d)
  other=$(mktemp -d)
  trap "rm -rf '$dir' '$other'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"
  write_claude_md "$dir/CLAUDE.md" "0.5.7"
  printf 'STALE\n' > "$dir/AGENTS.md"

  # The other tree is a complete, self-consistent repo root: it has its own
  # CLAUDE.md, so the generator running in ITS frame succeeds and exits 0.
  install_agents_generator "$other"
  write_claude_md "$other/CLAUDE.md" "9.9.9"
  mkdir -p "$dir/scripts"
  ln -sf "$other/scripts/gen-agents-md.mjs" "$dir/scripts/gen-agents-md.mjs"

  # Must fail...
  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) > /dev/null 2>&1 && return 1
  # ...and say which tree it is complaining about.
  local out
  out=$( (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) 2>&1 || true )
  echo "$out" | grep -q "not in sync" || return 1

  # The evidence the old check could not see: the caller's mirror is still
  # stale, while the generator's own tree was regenerated quite happily.
  grep -q '^STALE$' "$dir/AGENTS.md" || return 1
  [ -f "$other/AGENTS.md" ] || return 1
  return 0
}

# The regression the first cut of #7231 introduced, and the reason the check is
# gated on a sentinel LINE rather than on node's exit code.
#
# The verifier imports the generator into its own process. A generator that
# declines to run via a MODULE-SCOPE `process.exit(0)` therefore ends the
# VERIFIER with status 0 — `if node …; then` takes the success branch, the
# reassuring line prints, and the mirror is left stale. `origin/main` caught this
# because it required --check's confirmation line; the exit-code-only version did
# not, which made it strictly weaker than what it replaced against the very
# defect class it exists to close.
#
# `if (!invokedDirectly) process.exit(0)` is not a contrived stub — it is a
# plausible way to write the guard, and #7222 is currently rewriting exactly that
# guard.
test_agents_md_fails_when_generator_exits_during_import() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"
  write_claude_md "$dir/CLAUDE.md" "0.5.7"
  printf 'STALE\n' > "$dir/AGENTS.md"

  mkdir -p "$dir/scripts"
  cat > "$dir/scripts/gen-agents-md.mjs" <<'STUB'
// Declines at MODULE SCOPE rather than by guarding a block. Running this as a
// CLI is a clean exit-0 no-op; IMPORTING it terminates the importing process.
const invokedDirectly = Boolean(process.argv[1] && process.argv[1].endsWith('gen-agents-md.mjs'))
if (!invokedDirectly) process.exit(0)
export function renderAgentsMd (claudeContents) {
  return '<!-- AUTO-GENERATED FROM CLAUDE.md -->\n\n' + claudeContents
}
STUB

  # Must fail...
  local out rc=0
  out=$( (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) 2>&1 ) || rc=$?
  [ "$rc" -ne 0 ] || return 1
  # ...must NOT have printed the false success...
  ! printf '%s' "$out" | grep -q 'AGENTS.md regenerated from CLAUDE.md' || return 1
  # ...and must name the actual cause rather than blaming drift.
  printf '%s' "$out" | grep -q 'produced no output at all' || return 1
  grep -q '^STALE$' "$dir/AGENTS.md" || return 1
  return 0
}

# A missing mirror is a distinct failure from a stale one, and reading ENOENT as
# "nothing to compare" would fail open on a tree that never generated AGENTS.md
# at all.
test_agents_md_fails_when_mirror_is_absent() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"
  write_claude_md "$dir/CLAUDE.md" "0.5.7"

  mkdir -p "$dir/scripts"
  cat > "$dir/scripts/gen-agents-md.mjs" <<'STUB'
export function renderAgentsMd (claudeContents) {
  return "<!-- AUTO-GENERATED FROM CLAUDE.md -->\n\n" + claudeContents
}
STUB

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) > /dev/null 2>&1 && return 1
  [ ! -f "$dir/AGENTS.md" ] || return 1
  return 0
}

# --- runner ------------------------------------------------------------------

echo "Running bump-version.sh tests"
echo "============================="
run_test "scaffolds a new CHANGELOG section with today's date" \
  test_scaffolds_new_section
run_test "inserts the new section below [Unreleased], above the prior release (#5207)" \
  test_inserts_after_unreleased_section
run_test "preserves the Keep-a-Changelog header preamble" \
  test_preserves_header_preamble
run_test "is idempotent when a section for the new version already exists" \
  test_idempotent_when_section_exists
run_test "blocks the bump when the prior section still has a TODO" \
  test_blocks_when_prior_todo_unresolved
run_test "--no-changelog flag skips the scaffold and TODO check" \
  test_no_changelog_flag_skips_scaffold
run_test "--no-changelog flag works in either argument order" \
  test_no_changelog_flag_before_version
run_test "auto-bumps patch version and scaffolds the new section" \
  test_auto_bump_patch_with_scaffold
run_test "TODO check is scoped to the most-recent section only" \
  test_only_checks_most_recent_section_for_todo
run_test "--help prints the full header (Usage + CHANGELOG scaffolding)" \
  test_help_prints_full_header
run_test "rejects unknown flags" \
  test_rejects_unknown_flag
run_test "Cargo.lock awk fallback rewrites only the chroxy-desktop stanza" \
  test_lockfile_awk_rewrites_only_chroxy_desktop
run_test "Cargo.lock verify aborts when chroxy-desktop stanza is missing" \
  test_lockfile_verify_fails_when_stanza_missing
run_test "Cargo.lock sync uses cargo when on PATH (no awk fallthrough)" \
  test_lockfile_uses_cargo_when_on_path
run_test "bumps workspace @chroxy/* dependency ranges with the version" \
  test_bumps_workspace_chroxy_dep_ranges
run_test "bumps the version references in CLAUDE.md" \
  test_bumps_claude_md_version_references
run_test "bump still succeeds when CLAUDE.md is absent" \
  test_bump_survives_missing_claude_md
run_test "aborts when CLAUDE.md's version line format changed" \
  test_aborts_when_claude_md_format_changed

# --- AGENTS.md regeneration is VERIFIED, not announced (#7227) ---------------
#
# Before this, bump-version.sh printed "AGENTS.md regenerated from CLAUDE.md"
# on the generator merely having been invoked. `set -euo pipefail` catches a
# NON-ZERO exit; this whole defect class (#7198 / #7214) is exit ZERO having
# done nothing, so the release printed a false success and carried a stale
# AGENTS.md into the CI drift gate.
#
# The generator is stubbed rather than copied. What is under test is the
# CALLER's ability to distinguish "regenerated" from "silently skipped", and a
# stub can produce the skipped shape on demand — which the real generator, now
# that #7224 fixed it, no longer can.
#
#   healthy — writes AGENTS.md, and --check confirms with the real generator's
#             wording
#   quiet   — the authentic #7198 shape: BOTH invocations return without doing
#             anything, exit 0, print nothing. This is the case an exit-code
#             check cannot see, because --check is skipped too.
#   nowrite — the write is skipped but --check still works, so it reports drift
#             on stderr and exits 1
install_gen_agents_stub() {
  local dir="$1" mode="$2"
  mkdir -p "$dir/scripts"
  cat > "$dir/scripts/gen-agents-md.mjs" <<STUB
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
const mode = '$mode'

// The pure renderer, exported the way the real generator exports it. Since
// #7231 this is what bump-version.sh imports to verify in its OWN frame, so it
// has to be reachable WITHOUT running the CLI.
export function renderAgentsMd (claudeContents) {
  return 'GENERATED\n' + claudeContents
}

// Stands in for the real entry-point guard, and the reason the module-scope
// \`process.exit(0)\` these stubs used to open with had to go: that exit fired
// during the verifier's \`await import()\` too, killing the verifying process
// with status 0 — which the shell would have read as a PASS. A generator whose
// guard reads false does not exit, it simply declines to run, and a stub that
// models it any other way tests the stub instead of the script.
const invokedDirectly = Boolean(process.argv[1] && process.argv[1].endsWith('gen-agents-md.mjs'))
if (invokedDirectly) {
  const check = process.argv.includes('--check')
  // 'quiet' is the silent no-op: no output, exit 0, for BOTH invocations.
  // 'nowrite' skips only the write, so a --check invocation still reports drift.
  const skip = mode === 'quiet' || (mode === 'nowrite' && !check)
  if (!skip) {
    const claude = existsSync('CLAUDE.md') ? readFileSync('CLAUDE.md', 'utf8') : ''
    const want = renderAgentsMd(claude)
    if (check) {
      const have = existsSync('AGENTS.md') ? readFileSync('AGENTS.md', 'utf8') : ''
      if (have !== want) {
        console.error('::error::AGENTS.md is out of sync with CLAUDE.md.')
        process.exit(1)
      }
      console.log('AGENTS.md is in sync with CLAUDE.md.')
    } else {
      writeFileSync('AGENTS.md', want)
    }
  }
}
STUB
}

# Shared fixture for the three cases below.
setup_agents_case() {
  local dir="$1" mode="$2"
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  install_gen_agents_stub "$dir" "$mode"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"
  write_claude_md "$dir/CLAUDE.md" "0.5.7"
  printf 'STALE\n' > "$dir/AGENTS.md"
}

# Positive control. Without it, a check that rejected EVERY generator would
# pass the two failure cases below and look like a working guard.
test_agents_md_regeneration_succeeds() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  setup_agents_case "$dir" "healthy"

  local out
  out=$( (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) 2>&1 ) || return 1
  printf '%s' "$out" | grep -q 'AGENTS.md regenerated from CLAUDE.md' || return 1
  # ...and it actually wrote, rather than the message being decorative again.
  grep -q '^GENERATED$' "$dir/AGENTS.md" || return 1
  ! grep -q '^STALE$' "$dir/AGENTS.md" || return 1
}

# The authentic #7198 shape, and the one an exit-code-only check misses: the
# entry-point guard reads false, so the write AND --check are both skipped,
# both exit 0, and --check prints nothing.
test_agents_md_silent_noop_fails_the_bump() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  setup_agents_case "$dir" "quiet"

  local out rc=0
  out=$( (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) 2>&1 ) || rc=$?
  [ "$rc" -ne 0 ] || return 1
  printf '%s' "$out" | grep -q 'is not in sync with' || return 1
  # The false success must NOT also have been printed.
  ! printf '%s' "$out" | grep -q 'AGENTS.md regenerated from CLAUDE.md' || return 1
}

# The write is skipped but --check still runs, so it reports drift and exits 1.
test_agents_md_stale_after_regeneration_fails_the_bump() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  setup_agents_case "$dir" "nowrite"

  local out rc=0
  out=$( (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.6.0) 2>&1 ) || rc=$?
  [ "$rc" -ne 0 ] || return 1
  printf '%s' "$out" | grep -q 'is not in sync with' || return 1
  ! printf '%s' "$out" | grep -q 'AGENTS.md regenerated from CLAUDE.md' || return 1
}

run_test "AGENTS.md regeneration reports success when it really regenerated" \
  test_agents_md_regeneration_succeeds
run_test "a generator that silently no-ops fails the bump (#7198 shape)" \
  test_agents_md_silent_noop_fails_the_bump
run_test "a stale AGENTS.md after regeneration fails the bump" \
  test_agents_md_stale_after_regeneration_fails_the_bump
run_test "AGENTS.md is verified against \$ROOT, with the real generator (#7231)" \
  test_agents_md_regenerated_and_verified_in_root_frame
run_test "a generator writing to ANOTHER tree fails the bump (#7231)" \
  test_agents_md_fails_when_generator_writes_to_another_tree
run_test "an absent AGENTS.md fails the bump rather than reading as nothing-to-compare" \
  test_agents_md_fails_when_mirror_is_absent
run_test "a generator that exits during IMPORT fails the bump (#7231 regression)" \
  test_agents_md_fails_when_generator_exits_during_import

echo ""
echo "Results: $PASS passed, $FAIL failed"
if [ "$FAIL" -gt 0 ]; then
  echo "Failed tests:"
  for t in "${FAILED_TESTS[@]}"; do
    echo "  - $t"
  done
  exit 1
fi
