#!/usr/bin/env bash
#
# bump-version.test.sh — Self-contained test harness for scripts/bump-version.sh.
#
# Runs in a temp dir with a minimal fake monorepo skeleton (just the file paths
# bump-version.sh writes to). Each test case asserts an observable behavior of
# the script. No external test framework — keeps CI dep surface zero.
#
# Run from repo root:
#   bash scripts/__tests__/bump-version.test.sh
#
# Exit status: 0 if all tests pass, 1 otherwise.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BUMP="$REPO_ROOT/scripts/bump-version.sh"

PASS=0
FAIL=0
FAILED_TESTS=()

# PATH stripped of cargo so the lockfile-sync block deterministically takes
# the awk-in-place fallback. Tests that need to exercise the `command -v
# cargo` branch install a stub via install_cargo_stub() and prepend its
# directory to this value.
#
# Computed by walking the inherited $PATH and dropping every entry that
# actually contains a `cargo` executable. The remaining entries still give
# the script `node`, `awk`, `grep`, `sed`, `date`, etc. — every other
# external tool bump-version.sh shells out to. A hardcoded list would have
# to track per-runner Node layouts (CI uses /opt/hostedtoolcache, devs use
# /opt/homebrew or volta, nix uses /nix/store, etc.).
__strip_cargo_from_path() {
  local p="$1"
  local out=""
  local IFS=":"
  for d in $p; do
    [ -n "$d" ] || continue
    [ -x "$d/cargo" ] && continue
    if [ -z "$out" ]; then
      out="$d"
    else
      out="$out:$d"
    fi
  done
  printf '%s\n' "$out"
}
NOCARGO_PATH="$(__strip_cargo_from_path "$PATH")"

# --- helpers -----------------------------------------------------------------

# Build a minimal fake repo at $1 that satisfies every path bump-version.sh
# touches. Versions all start at $2.
#
# Cargo.lock includes a realistic `chroxy-desktop` stanza AND a transitive
# dependency at the same version — the lockfile-sync block must only rewrite
# the workspace stanza, never the look-alike transitive. The harness reuses
# the same fixture so every successful-bump test indirectly guards against the
# false-match regression.
build_fake_repo() {
  local dir="$1"
  local v="$2"
  mkdir -p "$dir/packages/server" "$dir/packages/app/ios/Chroxy" \
           "$dir/packages/desktop/src-tauri" "$dir/packages/protocol" \
           "$dir/packages/store-core" "$dir/packages/dashboard" \
           "$dir/packages/claude-hooks" "$dir/packages/design-tokens"

  for pkg in server app desktop protocol store-core dashboard claude-hooks design-tokens; do
    printf '{"name":"%s","version":"%s"}\n' "$pkg" "$v" \
      > "$dir/packages/$pkg/package.json"
  done
  printf '{"name":"chroxy","version":"%s"}\n' "$v" > "$dir/package.json"
  printf '{"expo":{"name":"chroxy","version":"%s"}}\n' "$v" \
    > "$dir/packages/app/app.json"
  printf '{"version":"%s"}\n' "$v" \
    > "$dir/packages/desktop/src-tauri/tauri.conf.json"
  cat > "$dir/packages/desktop/src-tauri/Cargo.toml" <<EOF
[package]
name = "chroxy-desktop"
version = "$v"
edition = "2021"
EOF
  cat > "$dir/packages/app/ios/Chroxy/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
  <key>CFBundleShortVersionString</key>
  <string>$v</string>
</dict>
</plist>
EOF
  printf '{"version":"%s","packages":{"":{"version":"%s"}}}\n' "$v" "$v" \
    > "$dir/package-lock.json"
  printf '{"version":"%s","packages":{"":{"version":"%s"}}}\n' "$v" "$v" \
    > "$dir/packages/server/package-lock.json"

  # Minimal Cargo.lock mirroring the shape of the real one. The decoy stanza
  # is a synthetic transitive at the same version — the lockfile-sync block
  # must scope its rewrite to the `chroxy-desktop` stanza only.
  cat > "$dir/packages/desktop/src-tauri/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "decoy-dep"
version = "$v"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"

[[package]]
name = "chroxy-desktop"
version = "$v"
dependencies = [
 "serde",
 "tauri",
]

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafebabe"
EOF
}

# Copy bump-version.sh into the fake repo. No source mutation — the script
# runs as-is, and PATH control (via NOCARGO_PATH / install_cargo_stub) picks
# which branch of the lockfile-sync block is exercised.
install_bump_script() {
  local dir="$1"
  mkdir -p "$dir/scripts"
  cp "$BUMP" "$dir/scripts/bump-version.sh"
  chmod +x "$dir/scripts/bump-version.sh"
}

# Install a `cargo` shim that performs the same in-place rewrite the awk
# fallback would, and drops a sentinel file so tests can assert the cargo
# branch was actually taken (i.e., the script didn't fall through to awk).
# Returns the directory holding the shim — caller is responsible for putting
# it on $PATH before running the bump.
install_cargo_stub() {
  local dir="$1"
  local stubdir="$dir/.stub-bin"
  mkdir -p "$stubdir"
  cat > "$stubdir/cargo" <<'STUB'
#!/usr/bin/env bash
# Minimal cargo stub: parse --precise <V> from argv, rewrite the
# chroxy-desktop stanza in ./Cargo.lock, drop a sentinel so the test can
# prove this branch ran instead of the awk fallback.
set -euo pipefail
new=""
while [ $# -gt 0 ]; do
  case "$1" in
    --precise) new="$2"; shift 2 ;;
    *) shift ;;
  esac
done
[ -n "$new" ] || { echo "cargo stub: missing --precise" >&2; exit 1; }
: > "$PWD/.cargo-stub-ran"
tmp="$PWD/Cargo.lock.stub.tmp"
awk -v new="$new" '
  /^\[\[package\]\]/ { in_pkg = 1; is_target = 0 }
  in_pkg && /^name = "chroxy-desktop"$/ { is_target = 1 }
  in_pkg && is_target && /^version = "/ {
    sub(/^version = "[^"]*"/, "version = \"" new "\"")
    is_target = 0
  }
  /^$/ { in_pkg = 0; is_target = 0 }
  { print }
' "$PWD/Cargo.lock" > "$tmp" && mv "$tmp" "$PWD/Cargo.lock"
STUB
  chmod +x "$stubdir/cargo"
  echo "$stubdir"
}

# Write a minimal CHANGELOG.md (header + one prior section).
write_changelog() {
  local file="$1"
  local prev_version="$2"
  local prev_body="$3"
  cat > "$file" <<EOF
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [$prev_version] - 2026-01-01

$prev_body
EOF
}

run_test() {
  local name="$1"
  shift
  if "$@"; then
    PASS=$((PASS + 1))
    echo "  PASS  $name"
  else
    FAIL=$((FAIL + 1))
    FAILED_TESTS+=("$name")
    echo "  FAIL  $name"
  fi
}

# --- test cases --------------------------------------------------------------

test_scaffolds_new_section() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- Some prior fix (#1)"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # New section header present, on its own line, with today's date
  local today
  today=$(date +%Y-%m-%d)
  grep -q "^## \[0.2.0\] - $today\$" "$dir/CHANGELOG.md" || {
    echo "    expected: ## [0.2.0] - $today" >&2
    return 1
  }

  # All three placeholder sections present
  grep -q "^### Added\$" "$dir/CHANGELOG.md" || return 1
  grep -q "^### Changed\$" "$dir/CHANGELOG.md" || return 1
  grep -q "^### Fixed\$" "$dir/CHANGELOG.md" || return 1

  # TODO markers present (drift guard fodder)
  [ "$(grep -c '^- TODO:' "$dir/CHANGELOG.md")" -eq 3 ] || return 1

  # Prior section preserved
  grep -q "^## \[0.1.0\] - 2026-01-01" "$dir/CHANGELOG.md" || return 1
  grep -q "Some prior fix" "$dir/CHANGELOG.md" || return 1

  # New section appears BEFORE the prior section (Keep-a-Changelog ordering)
  local new_line prev_line
  new_line=$(grep -n "^## \[0.2.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  prev_line=$(grep -n "^## \[0.1.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  [ "$new_line" -lt "$prev_line" ]
}

test_inserts_after_unreleased_section() {
  # #5207 — when the CHANGELOG has an [Unreleased] section on top, the new
  # versioned section must land directly BELOW it (and its body), not above —
  # preserving Keep-a-Changelog ordering and not burying pending entries.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

The format is based on [Keep a Changelog]; [Unreleased] stays on top.

## [Unreleased]

### Added

- A pending entry not yet released

## [0.1.0] - 2026-01-01

### Added

- Initial release
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  grep -q "^## \[0.2.0\] - " "$dir/CHANGELOG.md" || return 1

  # Ordering must be: [Unreleased] < [0.2.0] < [0.1.0]
  local unrel_line new_line prev_line
  unrel_line=$(grep -n "^## \[Unreleased\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  new_line=$(grep -n "^## \[0.2.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  prev_line=$(grep -n "^## \[0.1.0\]" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  [ "$unrel_line" -lt "$new_line" ] || {
    echo "    new section landed above [Unreleased] (line $new_line vs $unrel_line)" >&2
    return 1
  }
  [ "$new_line" -lt "$prev_line" ] || {
    echo "    new section landed below the prior release (line $new_line vs $prev_line)" >&2
    return 1
  }

  # The pending [Unreleased] entry must be preserved (not buried/dropped) AND
  # stay above the new version header — i.e. the new section must land below the
  # [Unreleased] *body*, not immediately after the `## [Unreleased]` line (which
  # would push the pending entry under the cut release). Assert by line number,
  # not just existence, so a regression that splices after the header line fails.
  local pending_line
  pending_line=$(grep -n "A pending entry not yet released" "$dir/CHANGELOG.md" | head -1 | cut -d: -f1)
  [ -n "$pending_line" ] || {
    echo "    pending [Unreleased] entry was dropped" >&2
    return 1
  }
  [ "$pending_line" -lt "$new_line" ] || {
    echo "    pending [Unreleased] entry landed below the new section (line $pending_line vs $new_line)" >&2
    return 1
  }
}

test_preserves_header_preamble() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Added

- Initial release"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # The Keep-a-Changelog preamble lines must still be the first non-blank lines
  head -5 "$dir/CHANGELOG.md" | grep -q "^# Changelog\$" || return 1
  head -10 "$dir/CHANGELOG.md" | grep -q "Keep a Changelog" || return 1
}

test_idempotent_when_section_exists() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.2.0] - 2026-05-15

### Added

- Already documented this release manually

## [0.1.0] - 2026-01-01

### Added

- Initial release
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # The pre-existing 0.2.0 section must survive untouched — no duplicate
  # header, no TODO injection.
  [ "$(grep -c '^## \[0.2.0\]' "$dir/CHANGELOG.md")" -eq 1 ] || return 1
  ! grep -q "^- TODO:" "$dir/CHANGELOG.md" || return 1
  grep -q "Already documented this release manually" "$dir/CHANGELOG.md" || return 1
}

test_blocks_when_prior_todo_unresolved() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.1.0] - 2026-01-01

### Added

- TODO: describe additions for this release (or delete this section)
EOF

  local output
  output=$(cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0 2>&1)
  local status=$?

  # Script must exit non-zero
  [ "$status" -ne 0 ] || {
    echo "    expected non-zero exit, got 0" >&2
    return 1
  }

  # Error message must reference the TODO placeholder
  echo "$output" | grep -q "TODO" || {
    echo "    error message did not mention TODO: $output" >&2
    return 1
  }

  # CHANGELOG must be unchanged (no 0.2.0 section)
  ! grep -q "^## \[0.2.0\]" "$dir/CHANGELOG.md" || return 1
}

test_no_changelog_flag_skips_scaffold() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  # Deliberately set up a CHANGELOG with an unresolved TODO — the flag must
  # still allow the bump to proceed.
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.1.0] - 2026-01-01

### Added

- TODO: describe additions for this release (or delete this section)
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh --no-changelog 0.2.0) > /dev/null 2>&1 || return 1

  # Version files updated
  grep -qE '"version":\s*"0.2.0"' "$dir/packages/server/package.json" || return 1
  # CHANGELOG.md untouched (still no 0.2.0 section)
  ! grep -q "^## \[0.2.0\]" "$dir/CHANGELOG.md" || return 1
}

test_no_changelog_flag_before_version() {
  # Flag order must not matter — --no-changelog can come before or after the
  # version positional.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Added

- Initial release"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0 --no-changelog) > /dev/null 2>&1 || return 1
  ! grep -q "^## \[0.2.0\]" "$dir/CHANGELOG.md" || return 1
}

test_auto_bump_patch_with_scaffold() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.5.7"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.5.7" "### Fixed

- A real fix (#42)"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh) > /dev/null 2>&1 || return 1

  # Auto-bumped to 0.5.8 and scaffolded
  grep -qE '"version":\s*"0.5.8"' "$dir/packages/server/package.json" || return 1
  grep -q "^## \[0.5.8\] - " "$dir/CHANGELOG.md" || return 1
}

test_only_checks_most_recent_section_for_todo() {
  # A stale TODO in an OLD section (older than the most-recent) must NOT block
  # the bump — otherwise every bump after a missed CHANGELOG update would be
  # permanently blocked.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.2.0"
  install_bump_script "$dir"
  cat > "$dir/CHANGELOG.md" <<'EOF'
# Changelog

## [0.2.0] - 2026-02-01

### Added

- Properly documented this one

## [0.1.0] - 2026-01-01

### Added

- TODO: describe additions for this release (or delete this section)
EOF

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.3.0) > /dev/null 2>&1 || {
    echo "    bump unexpectedly failed despite stale TODO being in OLD section" >&2
    return 1
  }
  grep -q "^## \[0.3.0\]" "$dir/CHANGELOG.md" || return 1
}

test_help_prints_full_header() {
  # The header comment block expanded from 9 lines to 16+ in this PR. Earlier
  # versions of --help printed a hardcoded line range (2,11) and silently
  # truncated. Lock the contract: --help must include both the usage block
  # AND the CHANGELOG scaffolding paragraph.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"

  local output
  output=$(cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh --help 2>&1)
  [ $? -eq 0 ] || return 1

  echo "$output" | grep -q "Usage:" || {
    echo "    --help missing 'Usage:'" >&2
    return 1
  }
  echo "$output" | grep -q "no-changelog" || {
    echo "    --help missing '--no-changelog' line" >&2
    return 1
  }
  echo "$output" | grep -q "CHANGELOG scaffolding" || {
    echo "    --help truncated before CHANGELOG scaffolding paragraph" >&2
    return 1
  }
}

test_rejects_unknown_flag() {
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh --bogus-flag 0.2.0) > /dev/null 2>&1
  [ $? -ne 0 ]
}

# --- Cargo.lock sync coverage (#4253) ---------------------------------------

test_lockfile_awk_rewrites_only_chroxy_desktop() {
  # The awk fallback must rewrite the `chroxy-desktop` stanza only — a
  # transitive dep that happens to share the same version string must stay
  # pinned to its original version.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  (cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  local lock="$dir/packages/desktop/src-tauri/Cargo.lock"

  # The chroxy-desktop stanza moved to 0.2.0.
  awk '
    /^\[\[package\]\]/ { in_pkg = 1; is_target = 0; next }
    in_pkg && /^name = "chroxy-desktop"$/ { is_target = 1; next }
    in_pkg && is_target && /^version = "/ {
      sub(/^version = "/, ""); sub(/".*$/, ""); print; exit
    }
    /^$/ { in_pkg = 0; is_target = 0 }
  ' "$lock" | grep -qx "0.2.0" || {
    echo "    chroxy-desktop stanza did not move to 0.2.0" >&2
    return 1
  }

  # The decoy stanza (same starting version, different name) stayed at 0.1.0
  # — a bare grep/sed on `version = "0.1.0"` would have rewritten this too.
  awk '
    /^\[\[package\]\]/ { in_pkg = 1; is_target = 0; next }
    in_pkg && /^name = "decoy-dep"$/ { is_target = 1; next }
    in_pkg && is_target && /^version = "/ {
      sub(/^version = "/, ""); sub(/".*$/, ""); print; exit
    }
    /^$/ { in_pkg = 0; is_target = 0 }
  ' "$lock" | grep -qx "0.1.0" || {
    echo "    decoy-dep stanza was incorrectly rewritten (false-match regression)" >&2
    return 1
  }
}

test_lockfile_verify_fails_when_stanza_missing() {
  # If Cargo.lock has no chroxy-desktop stanza (corruption, accidental
  # delete, untracked checkout), the post-verify must abort with a non-zero
  # exit — silent success would let CI ship a stale lockfile.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  # Replace the seeded Cargo.lock with one missing the chroxy-desktop stanza.
  cat > "$dir/packages/desktop/src-tauri/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafebabe"
EOF

  local output status
  output=$(cd "$dir" && PATH="$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0 2>&1)
  status=$?

  [ "$status" -ne 0 ] || {
    echo "    expected non-zero exit when chroxy-desktop stanza is missing, got 0" >&2
    return 1
  }
  echo "$output" | grep -q "Cargo.lock" || {
    echo "    error message did not mention Cargo.lock: $output" >&2
    return 1
  }
}

test_lockfile_uses_cargo_when_on_path() {
  # When cargo is on PATH, the script must take the cargo branch and not
  # fall through to the awk fallback. Detect via a sentinel file the stub
  # drops next to Cargo.lock — the awk path never touches that file.
  local dir
  dir=$(mktemp -d)
  trap "rm -rf '$dir'" RETURN
  build_fake_repo "$dir" "0.1.0"
  install_bump_script "$dir"
  write_changelog "$dir/CHANGELOG.md" "0.1.0" "### Fixed

- prior"

  local stubdir
  stubdir=$(install_cargo_stub "$dir")

  (cd "$dir" && PATH="$stubdir:$NOCARGO_PATH" ./scripts/bump-version.sh 0.2.0) > /dev/null 2>&1 || return 1

  # Stub left its sentinel — proves the cargo branch ran.
  [ -f "$dir/packages/desktop/src-tauri/.cargo-stub-ran" ] || {
    echo "    cargo stub sentinel missing — script fell through to awk fallback" >&2
    return 1
  }

  # And the lockfile is still consistent (stub uses the same awk edit).
  local lock="$dir/packages/desktop/src-tauri/Cargo.lock"
  awk '
    /^\[\[package\]\]/ { in_pkg = 1; is_target = 0; next }
    in_pkg && /^name = "chroxy-desktop"$/ { is_target = 1; next }
    in_pkg && is_target && /^version = "/ {
      sub(/^version = "/, ""); sub(/".*$/, ""); print; exit
    }
    /^$/ { in_pkg = 0; is_target = 0 }
  ' "$lock" | grep -qx "0.2.0"
}

# --- runner ------------------------------------------------------------------

echo "Running bump-version.sh tests"
echo "============================="
run_test "scaffolds a new CHANGELOG section with today's date" \
  test_scaffolds_new_section
run_test "inserts the new section below [Unreleased], above the prior release (#5207)" \
  test_inserts_after_unreleased_section
run_test "preserves the Keep-a-Changelog header preamble" \
  test_preserves_header_preamble
run_test "is idempotent when a section for the new version already exists" \
  test_idempotent_when_section_exists
run_test "blocks the bump when the prior section still has a TODO" \
  test_blocks_when_prior_todo_unresolved
run_test "--no-changelog flag skips the scaffold and TODO check" \
  test_no_changelog_flag_skips_scaffold
run_test "--no-changelog flag works in either argument order" \
  test_no_changelog_flag_before_version
run_test "auto-bumps patch version and scaffolds the new section" \
  test_auto_bump_patch_with_scaffold
run_test "TODO check is scoped to the most-recent section only" \
  test_only_checks_most_recent_section_for_todo
run_test "--help prints the full header (Usage + CHANGELOG scaffolding)" \
  test_help_prints_full_header
run_test "rejects unknown flags" \
  test_rejects_unknown_flag
run_test "Cargo.lock awk fallback rewrites only the chroxy-desktop stanza" \
  test_lockfile_awk_rewrites_only_chroxy_desktop
run_test "Cargo.lock verify aborts when chroxy-desktop stanza is missing" \
  test_lockfile_verify_fails_when_stanza_missing
run_test "Cargo.lock sync uses cargo when on PATH (no awk fallthrough)" \
  test_lockfile_uses_cargo_when_on_path

echo ""
echo "Results: $PASS passed, $FAIL failed"
if [ "$FAIL" -gt 0 ]; then
  echo "Failed tests:"
  for t in "${FAILED_TESTS[@]}"; do
    echo "  - $t"
  done
  exit 1
fi
